Задание 1. Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [2]:
import numpy as np

np.arange( 9, -1, -1)
        




array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [9]:
x = np.diag(np.arange(9, -1, -1), k=0)
print(x)
x.sum()

[[9 0 0 0 0 0 0 0 0 0]
 [0 8 0 0 0 0 0 0 0 0]
 [0 0 7 0 0 0 0 0 0 0]
 [0 0 0 6 0 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0 0]
 [0 0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0]]


45

Задание 3
Решите систему уравнений:
4x + 2y + z = 4

x + 3y = 12

5y + 4z = -3

In [10]:
from numpy import linalg

a = np.array( [ [4., 2., 1.], [1., 3., 0.], [0., 5., 4.] ])

b = np.array( [4., 12., -3.] )


linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)
    
    
На сайт заходит очередной посетитель, о покупках которого известно следующее:

next_user_stats = np.array([0, 1, 2, 0, 0, 0])

Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [3]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

next_user_stats = np.array([0, 1, 2, 0, 0, 0])


def cosine(  users_stats, next_user_stats ):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """    
      
    i = 0
    for user in users_stats:
        aLength = np.linalg.norm( users_stats[i] )                # длины векторов
        bLength = np.linalg.norm( next_user_stats )
        i += 1
        return (np.dot( users_stats, next_user_stats )) / ( aLength * bLength )

cosine( users_stats, next_user_stats )

array([0.2, 1. , 0.4, 1. , 0.4, 0. , 0. , 0.6, 0. , 0. ])